steps:
- name: 'gcr.io/gcp-project-415616/gcpdevops'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']

- name: 'gcr.io/gcp-project-415616/gcpdevops'
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]

- name: 'gcr.io/gcp-project-415616/gkedeploy'
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-project
  - --namespace=gcp-project-prod
  

